---
- name: INSTALL | Ensure old docker packages are uninstalled
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: INSTALL | Install dependent packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: INSTALL | Add docker repository apt key
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/debian/gpg

# TODO - make sure we can handle lsb_release version here
- name: INSTALL | Add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
    state: present
    update_cache: yes

- name: INSTALL | Install docker CE packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: true
    state: present
